
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-batch-volcano-sh-v1alpha1-jobflow
  failurePolicy: Fail
  name: mjobflow.kb.io
  rules:
  - apiGroups:
    - flow.volcano.sh
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobflows
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-batch-volcano-sh-v1alpha1-jobtemplate
  failurePolicy: Fail
  name: mjobtemplate.kb.io
  rules:
  - apiGroups:
    - flow.volcano.sh
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobtemplates
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-batch-volcano-sh-v1alpha1-jobflow
  failurePolicy: Fail
  name: vjobflow.kb.io
  rules:
  - apiGroups:
    - flow.volcano.sh
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobflows
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-batch-volcano-sh-v1alpha1-jobtemplate
  failurePolicy: Fail
  name: vjobtemplate.kb.io
  rules:
  - apiGroups:
    - flow.volcano.sh
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobtemplates
  sideEffects: None
