# permissions for end users to view jobflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jobflow-viewer-role
rules:
- apiGroups:
  - batch.volcano.sh
  resources:
  - jobflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.volcano.sh
  resources:
  - jobflows/status
  verbs:
  - get
