# permissions for end users to view jobtemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jobtemplate-viewer-role
rules:
- apiGroups:
  - batch.volcano.sh
  resources:
  - jobtemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.volcano.sh
  resources:
  - jobtemplates/status
  verbs:
  - get
