apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: jobflow-system/jobflow-serving-cert
  name: jobflow-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    service:
      name: jobflow-webhook-service
      namespace: jobflow-system
      path: /validate-batch-volcano-sh-v1alpha1-jobflow
  failurePolicy: Fail
  name: vjobflow.kb.io
  rules:
  - apiGroups:
    - batch.volcano.sh
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobflows
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    service:
      name: jobflow-webhook-service
      namespace: jobflow-system
      path: /validate-batch-volcano-sh-v1alpha1-jobtemplate
  failurePolicy: Fail
  name: vjobtemplate.kb.io
  rules:
  - apiGroups:
    - batch.volcano.sh
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobtemplates
  sideEffects: None
