apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: jobflow-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURSVENDQWkyZ0F3SUJBZ0lVQjFpdjBRMjVxRDdIZGUrN0hpcTVqV2x3L0lvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd01qRXdNQzRHQTFVRUF3d25hbTlpWm14dmR5MTNaV0pvYjI5ckxYTmxjblpwWTJVdWEzVmlaUzF6ZVhOMApaVzB1YzNaak1CNFhEVEl4TVRFeE9EQTNNRFF4TkZvWERUTXhNVEV4TmpBM01EUXhORm93TWpFd01DNEdBMVVFCkF3d25hbTlpWm14dmR5MTNaV0pvYjI5ckxYTmxjblpwWTJVdWEzVmlaUzF6ZVhOMFpXMHVjM1pqTUlJQklqQU4KQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBKzVTV2dRZzc2Mm5yM05iaWJ2ajJzd2xIYkVSQQo0aUx5dXNhcDFpaHVRVzQ1NWFPT0s4dVRVcTBXUGZyT0NGdVhyVm1tQzU2WENPVW9CaU54YmhoMmhUckw1bjZXClhkNkxYY24zczEzUWE5cVhtTWk1R01JNUNzK3RITlJ6eVB1Ui9mYlVXOWEva25RQWNKS2pCQm50eGt6NEJwSHcKWkM0amZmZnJieDRldDU1QVJQLzhxcUd0VTRIdVVVNTArOE1MM2UxQmFiQUpWVURFajlMM09tcXF6RncvVEhmKwppRkFwVTZ3VTZMWE91VnpuNWdBUEJFMXIvN25YMkFjNU1nazJJYlFadjJhZHZXcmJkMER2TFlxcUlUbnhvdUNICnR0OXBEK3I2aE5CQUZXSDdKcW5Ldk5taVcxbnhqa216d2lQS3JDOFkyOHhiY0cvZVF4aDlCM1VMM3dJREFRQUIKbzFNd1VUQWRCZ05WSFE0RUZnUVVaUjVIa1BQOE01OGJnTE1tK2ZFY2lxN29uZXN3SHdZRFZSMGpCQmd3Rm9BVQpaUjVIa1BQOE01OGJnTE1tK2ZFY2lxN29uZXN3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCCkFRc0ZBQU9DQVFFQXArSERZSzRTQStJR0FIU2Z0OFR6SC9FTXIzeTNxQTRnUWl1bFBub2trZU84S09GRXVVMGIKWjVxcnorMWg0ZFVFWWNuaXFMUnMrdXhTNUpFdzZMcURHY1FqaU1JSnhGR1ZkRC9BYm9MM24rTW5kZ1NlVXNXLwpxNkJHcmM5YjNZWW83TWxuRlZwRVQ0aGZPNE9aYVpSMGt4clM3L0FWSGtmSUFydGo4YW9BYzF6Q0ErWFN0Z2NDCndzTlNJUExzZ1F5WnNtangzSlg0U2Rhb2hnRWMxaEkzRGVIcmwxZE8vTXhWdXRWYmxZRDJXei9PaXFWejlPVm8KWHV5bzFJcTZGQXdWL2pXSHZza2VuUE9MZm1TTGIwNU5xRnJITXZOcDJFTHJUOTh0MzBnNkNzRkpGZUJBZGRWWQpJMzdjQ1NONlpjY1B3Qzl2RGxrbVhacnE4YjAwMVp0VzFBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: jobflow-webhook-service
      namespace: kube-system
      path: /mutate-batch-volcano-sh-v1alpha1-jobtemplate
  failurePolicy: Fail
  name: mjobtemplate.kb.io
  rules:
  - apiGroups:
    - batch.volcano.sh
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobtemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1alpha1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURSVENDQWkyZ0F3SUJBZ0lVQjFpdjBRMjVxRDdIZGUrN0hpcTVqV2x3L0lvd0RRWUpLb1pJaHZjTkFRRUwKQlFBd01qRXdNQzRHQTFVRUF3d25hbTlpWm14dmR5MTNaV0pvYjI5ckxYTmxjblpwWTJVdWEzVmlaUzF6ZVhOMApaVzB1YzNaak1CNFhEVEl4TVRFeE9EQTNNRFF4TkZvWERUTXhNVEV4TmpBM01EUXhORm93TWpFd01DNEdBMVVFCkF3d25hbTlpWm14dmR5MTNaV0pvYjI5ckxYTmxjblpwWTJVdWEzVmlaUzF6ZVhOMFpXMHVjM1pqTUlJQklqQU4KQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBKzVTV2dRZzc2Mm5yM05iaWJ2ajJzd2xIYkVSQQo0aUx5dXNhcDFpaHVRVzQ1NWFPT0s4dVRVcTBXUGZyT0NGdVhyVm1tQzU2WENPVW9CaU54YmhoMmhUckw1bjZXClhkNkxYY24zczEzUWE5cVhtTWk1R01JNUNzK3RITlJ6eVB1Ui9mYlVXOWEva25RQWNKS2pCQm50eGt6NEJwSHcKWkM0amZmZnJieDRldDU1QVJQLzhxcUd0VTRIdVVVNTArOE1MM2UxQmFiQUpWVURFajlMM09tcXF6RncvVEhmKwppRkFwVTZ3VTZMWE91VnpuNWdBUEJFMXIvN25YMkFjNU1nazJJYlFadjJhZHZXcmJkMER2TFlxcUlUbnhvdUNICnR0OXBEK3I2aE5CQUZXSDdKcW5Ldk5taVcxbnhqa216d2lQS3JDOFkyOHhiY0cvZVF4aDlCM1VMM3dJREFRQUIKbzFNd1VUQWRCZ05WSFE0RUZnUVVaUjVIa1BQOE01OGJnTE1tK2ZFY2lxN29uZXN3SHdZRFZSMGpCQmd3Rm9BVQpaUjVIa1BQOE01OGJnTE1tK2ZFY2lxN29uZXN3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFOQmdrcWhraUc5dzBCCkFRc0ZBQU9DQVFFQXArSERZSzRTQStJR0FIU2Z0OFR6SC9FTXIzeTNxQTRnUWl1bFBub2trZU84S09GRXVVMGIKWjVxcnorMWg0ZFVFWWNuaXFMUnMrdXhTNUpFdzZMcURHY1FqaU1JSnhGR1ZkRC9BYm9MM24rTW5kZ1NlVXNXLwpxNkJHcmM5YjNZWW83TWxuRlZwRVQ0aGZPNE9aYVpSMGt4clM3L0FWSGtmSUFydGo4YW9BYzF6Q0ErWFN0Z2NDCndzTlNJUExzZ1F5WnNtangzSlg0U2Rhb2hnRWMxaEkzRGVIcmwxZE8vTXhWdXRWYmxZRDJXei9PaXFWejlPVm8KWHV5bzFJcTZGQXdWL2pXSHZza2VuUE9MZm1TTGIwNU5xRnJITXZOcDJFTHJUOTh0MzBnNkNzRkpGZUJBZGRWWQpJMzdjQ1NONlpjY1B3Qzl2RGxrbVhacnE4YjAwMVp0VzFBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    service:
      name: jobflow-webhook-service
      namespace: kube-system
      path: /mutate-batch-volcano-sh-v1alpha1-jobflow
  failurePolicy: Fail
  name: mjobflow.kb.io
  rules:
  - apiGroups:
    - batch.volcano.sh
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - jobflows
  sideEffects: None
