apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jobflow-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jobflow-proxy-role
subjects:
- kind: ServiceAccount
  name: jobflow-controller-manager
  namespace: kube-system
